// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clear_users_table.sql

package database

import (
	"context"
)

const clearUsersTable = `-- name: ClearUsersTable :exec
TRUNCATE TABLE users
`

func (q *Queries) ClearUsersTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearUsersTable)
	return err
}
