// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_user_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setUserChirpyRed = `-- name: SetUserChirpyRed :one
UPDATE users
SET is_chirpy_red = $2
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type SetUserChirpyRedParams struct {
	ID          uuid.UUID
	IsChirpyRed bool
}

func (q *Queries) SetUserChirpyRed(ctx context.Context, arg SetUserChirpyRedParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserChirpyRed, arg.ID, arg.IsChirpyRed)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
